//
// AccountAuthorizedDepositorBadgeType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AccountAuthorizedDepositorBadgeType: String, Codable, CaseIterable {
    case resourceBadge = "ResourceBadge"
    case nonFungibleBadge = "NonFungibleBadge"
}
