//
// AccountDepositPreValidationNonFungibleBadgeAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountDepositPreValidationNonFungibleBadgeAllOf: Codable, JSONEncodable, Hashable {

    /** String-encoded non-fungible ID. */
    public var nonFungibleId: String

    public init(nonFungibleId: String) {
        self.nonFungibleId = nonFungibleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nonFungibleId = "non_fungible_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nonFungibleId, forKey: .nonFungibleId)
    }
}

