//
// AccountResourcePreferenceRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AccountResourcePreferenceRule: String, Codable, CaseIterable {
    case allowed = "Allowed"
    case disallowed = "Disallowed"
}
