//
// AccountDepositPreValidationDecidingFactorsResourceSpecificDetailsItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountDepositPreValidationDecidingFactorsResourceSpecificDetailsItem: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded human readable version of the address. */
    public var resourceAddress: String
    public var vaultExists: Bool
    public var isXrd: Bool
    public var resourcePreferenceRule: AccountResourcePreferenceRule?

    public init(resourceAddress: String, vaultExists: Bool, isXrd: Bool, resourcePreferenceRule: AccountResourcePreferenceRule? = nil) {
        self.resourceAddress = resourceAddress
        self.vaultExists = vaultExists
        self.isXrd = isXrd
        self.resourcePreferenceRule = resourcePreferenceRule
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceAddress = "resource_address"
        case vaultExists = "vault_exists"
        case isXrd = "is_xrd"
        case resourcePreferenceRule = "resource_preference_rule"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resourceAddress, forKey: .resourceAddress)
        try container.encode(vaultExists, forKey: .vaultExists)
        try container.encode(isXrd, forKey: .isXrd)
        try container.encodeIfPresent(resourcePreferenceRule, forKey: .resourcePreferenceRule)
    }
}

