//
// AtLedgerStateMixin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** defines upper boundary (inclusive) for queried data. i.e &#x60;{ \&quot;at_state_version\&quot; &#x3D; {\&quot;epoch\&quot; &#x3D; 10} }&#x60;, will return data till 10 epoch. */
public struct AtLedgerStateMixin: Codable, JSONEncodable, Hashable {

    public var atLedgerState: LedgerStateSelector?

    public init(atLedgerState: LedgerStateSelector? = nil) {
        self.atLedgerState = atLedgerState
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case atLedgerState = "at_ledger_state"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(atLedgerState, forKey: .atLedgerState)
    }
}

