//
// ComponentEntityRoleAssignments.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComponentEntityRoleAssignments: Codable, JSONEncodable, Hashable {

    /** This type is defined in the Core API as `OwnerRole`. See the Core API documentation for more details.  */
    public var owner: AnyCodable
    public var entries: [ComponentEntityRoleAssignmentEntry]

    public init(owner: AnyCodable, entries: [ComponentEntityRoleAssignmentEntry]) {
        self.owner = owner
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case owner
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(owner, forKey: .owner)
        try container.encode(entries, forKey: .entries)
    }
}

