//
// ComponentEntityRoleAssignmentEntryAssignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComponentEntityRoleAssignmentEntryAssignment: Codable, JSONEncodable, Hashable {

    public var resolution: RoleAssignmentResolution
    /** This type is defined in the Core API as `AccessRule`. See the Core API documentation for more details.  */
    public var explicitRule: AnyCodable?

    public init(resolution: RoleAssignmentResolution, explicitRule: AnyCodable? = nil) {
        self.resolution = resolution
        self.explicitRule = explicitRule
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resolution
        case explicitRule = "explicit_rule"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resolution, forKey: .resolution)
        try container.encodeIfPresent(explicitRule, forKey: .explicitRule)
    }
}

