//
// EntityMetadataItemValueAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EntityMetadataItemValueAllOf: Codable, JSONEncodable, Hashable {

    public var typed: MetadataTypedValue

    public init(typed: MetadataTypedValue) {
        self.typed = typed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case typed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(typed, forKey: .typed)
    }
}

