//
// EntitySchemaCollectionItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EntitySchemaCollectionItem: Codable, JSONEncodable, Hashable {

    /** Hex-encoded binary blob. */
    public var schemaHashHex: String
    /** Hex-encoded binary blob. */
    public var schemaHex: String

    public init(schemaHashHex: String, schemaHex: String) {
        self.schemaHashHex = schemaHashHex
        self.schemaHex = schemaHex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaHashHex = "schema_hash_hex"
        case schemaHex = "schema_hex"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schemaHashHex, forKey: .schemaHashHex)
        try container.encode(schemaHex, forKey: .schemaHex)
    }
}

