//
// GatewayStatusResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GatewayStatusResponseAllOf: Codable, JSONEncodable, Hashable {

    public var releaseInfo: GatewayInfoResponseReleaseInfo

    public init(releaseInfo: GatewayInfoResponseReleaseInfo) {
        self.releaseInfo = releaseInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case releaseInfo = "release_info"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(releaseInfo, forKey: .releaseInfo)
    }
}

