//
// GatewayStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GatewayStatusResponse: Codable, JSONEncodable, Hashable {

    public var ledgerState: LedgerState
    public var releaseInfo: GatewayInfoResponseReleaseInfo

    public init(ledgerState: LedgerState, releaseInfo: GatewayInfoResponseReleaseInfo) {
        self.ledgerState = ledgerState
        self.releaseInfo = releaseInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ledgerState = "ledger_state"
        case releaseInfo = "release_info"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ledgerState, forKey: .ledgerState)
        try container.encode(releaseInfo, forKey: .releaseInfo)
    }
}

