//
// InvalidEntityError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvalidEntityError: Codable, JSONEncodable, Hashable {

    /** The type of error. Each subtype may have its own additional structured fields. */
    public var type: String
    /** Bech32m-encoded human readable version of the address. */
    public var address: String

    public init(type: String, address: String) {
        self.type = type
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(address, forKey: .address)
    }
}

