//
// MetadataInstantArrayValueAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** See documentation of &#x60;MetadataInstantValue&#x60; for detailed description of &#x60;values&#x60; vs &#x60;values_unix_timestamp_seconds&#x60;.  */
public struct MetadataInstantArrayValueAllOf: Codable, JSONEncodable, Hashable {

    public var values: [String]
    public var valuesUnixTimestampSeconds: [String]

    public init(values: [String], valuesUnixTimestampSeconds: [String]) {
        self.values = values
        self.valuesUnixTimestampSeconds = valuesUnixTimestampSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case values
        case valuesUnixTimestampSeconds = "values_unix_timestamp_seconds"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(values, forKey: .values)
        try container.encode(valuesUnixTimestampSeconds, forKey: .valuesUnixTimestampSeconds)
    }
}

