//
// NetworkConfigurationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NetworkConfigurationResponse: Codable, JSONEncodable, Hashable {

    static let networkIdRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 255, exclusiveMaximum: false, multipleOf: nil)
    /** The logical id of the network */
    public var networkId: Int
    /** The logical name of the network */
    public var networkName: String
    public var wellKnownAddresses: NetworkConfigurationResponseWellKnownAddresses

    public init(networkId: Int, networkName: String, wellKnownAddresses: NetworkConfigurationResponseWellKnownAddresses) {
        self.networkId = networkId
        self.networkName = networkName
        self.wellKnownAddresses = wellKnownAddresses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networkId = "network_id"
        case networkName = "network_name"
        case wellKnownAddresses = "well_known_addresses"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(networkId, forKey: .networkId)
        try container.encode(networkName, forKey: .networkName)
        try container.encode(wellKnownAddresses, forKey: .wellKnownAddresses)
    }
}

