//
// NonFungibleResourcesCollectionItemVaultAggregatedVaultItemAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NonFungibleResourcesCollectionItemVaultAggregatedVaultItemAllOf: Codable, JSONEncodable, Hashable {

    static let lastUpdatedAtStateVersionRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: 100000000000000, exclusiveMaximum: false, multipleOf: nil)
    /** Bech32m-encoded human readable version of the address. */
    public var vaultAddress: String
    public var totalCount: Int64
    /** The most recent state version underlying object was modified at. */
    public var lastUpdatedAtStateVersion: Int64

    public init(vaultAddress: String, totalCount: Int64, lastUpdatedAtStateVersion: Int64) {
        self.vaultAddress = vaultAddress
        self.totalCount = totalCount
        self.lastUpdatedAtStateVersion = lastUpdatedAtStateVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vaultAddress = "vault_address"
        case totalCount = "total_count"
        case lastUpdatedAtStateVersion = "last_updated_at_state_version"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vaultAddress, forKey: .vaultAddress)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(lastUpdatedAtStateVersion, forKey: .lastUpdatedAtStateVersion)
    }
}

