//
// NonFungibleResourcesCollectionItemGloballyAggregated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NonFungibleResourcesCollectionItemGloballyAggregated: Codable, JSONEncodable, Hashable {

    static let lastUpdatedAtStateVersionRule = NumericRule<Int64>(minimum: 1, exclusiveMinimum: false, maximum: 100000000000000, exclusiveMaximum: false, multipleOf: nil)
    public var aggregationLevel: ResourceAggregationLevel
    /** Bech32m-encoded human readable version of the address. */
    public var resourceAddress: String
    public var explicitMetadata: EntityMetadataCollection?
    /** The total amount of non-fungible IDs across all vaults. */
    public var amount: Int64
    /** The most recent state version underlying object was modified at. */
    public var lastUpdatedAtStateVersion: Int64

    public init(aggregationLevel: ResourceAggregationLevel, resourceAddress: String, explicitMetadata: EntityMetadataCollection? = nil, amount: Int64, lastUpdatedAtStateVersion: Int64) {
        self.aggregationLevel = aggregationLevel
        self.resourceAddress = resourceAddress
        self.explicitMetadata = explicitMetadata
        self.amount = amount
        self.lastUpdatedAtStateVersion = lastUpdatedAtStateVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aggregationLevel = "aggregation_level"
        case resourceAddress = "resource_address"
        case explicitMetadata = "explicit_metadata"
        case amount
        case lastUpdatedAtStateVersion = "last_updated_at_state_version"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aggregationLevel, forKey: .aggregationLevel)
        try container.encode(resourceAddress, forKey: .resourceAddress)
        try container.encodeIfPresent(explicitMetadata, forKey: .explicitMetadata)
        try container.encode(amount, forKey: .amount)
        try container.encode(lastUpdatedAtStateVersion, forKey: .lastUpdatedAtStateVersion)
    }
}

