//
// ObjectModuleId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ObjectModuleId: String, Codable, CaseIterable {
    case main = "Main"
    case metadata = "Metadata"
    case royalty = "Royalty"
    case roleAssignment = "RoleAssignment"
}
