//
// PackageCodeCollectionItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PackageCodeCollectionItem: Codable, JSONEncodable, Hashable {

    public var vmType: PackageVmType
    /** Hex-encoded binary blob. */
    public var codeHashHex: String
    /** Hex-encoded binary blob. */
    public var codeHex: String

    public init(vmType: PackageVmType, codeHashHex: String, codeHex: String) {
        self.vmType = vmType
        self.codeHashHex = codeHashHex
        self.codeHex = codeHex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vmType = "vm_type"
        case codeHashHex = "code_hash_hex"
        case codeHex = "code_hex"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vmType, forKey: .vmType)
        try container.encode(codeHashHex, forKey: .codeHashHex)
        try container.encode(codeHex, forKey: .codeHex)
    }
}

