//
// PackageVmType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PackageVmType: String, Codable, CaseIterable {
    case native = "Native"
    case scryptoV1 = "ScryptoV1"
}
