//
// ProgrammaticScryptoSborValueBytesAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProgrammaticScryptoSborValueBytesAllOf: Codable, JSONEncodable, Hashable {

    public var elementKind: ProgrammaticScryptoSborValueKind
    public var elementTypeName: String?
    /** Hex-encoded binary blob. */
    public var hex: String

    public init(elementKind: ProgrammaticScryptoSborValueKind, elementTypeName: String? = nil, hex: String) {
        self.elementKind = elementKind
        self.elementTypeName = elementTypeName
        self.hex = hex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case elementKind = "element_kind"
        case elementTypeName = "element_type_name"
        case hex
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(elementKind, forKey: .elementKind)
        try container.encodeIfPresent(elementTypeName, forKey: .elementTypeName)
        try container.encode(hex, forKey: .hex)
    }
}

