//
// ProgrammaticScryptoSborValueMapAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProgrammaticScryptoSborValueMapAllOf: Codable, JSONEncodable, Hashable {

    public var keyKind: ProgrammaticScryptoSborValueKind
    public var keyTypeName: String?
    public var valueKind: ProgrammaticScryptoSborValueKind
    public var valueTypeName: String?
    public var entries: [ProgrammaticScryptoSborValueMapEntry]

    public init(keyKind: ProgrammaticScryptoSborValueKind, keyTypeName: String? = nil, valueKind: ProgrammaticScryptoSborValueKind, valueTypeName: String? = nil, entries: [ProgrammaticScryptoSborValueMapEntry]) {
        self.keyKind = keyKind
        self.keyTypeName = keyTypeName
        self.valueKind = valueKind
        self.valueTypeName = valueTypeName
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keyKind = "key_kind"
        case keyTypeName = "key_type_name"
        case valueKind = "value_kind"
        case valueTypeName = "value_type_name"
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keyKind, forKey: .keyKind)
        try container.encodeIfPresent(keyTypeName, forKey: .keyTypeName)
        try container.encode(valueKind, forKey: .valueKind)
        try container.encodeIfPresent(valueTypeName, forKey: .valueTypeName)
        try container.encode(entries, forKey: .entries)
    }
}

