//
// ProgrammaticScryptoSborValueTupleAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProgrammaticScryptoSborValueTupleAllOf: Codable, JSONEncodable, Hashable {

    public var fields: [ProgrammaticScryptoSborValue]

    public init(fields: [ProgrammaticScryptoSborValue]) {
        self.fields = fields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fields, forKey: .fields)
    }
}

