//
// PublicKeyHash.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicKeyHash: Codable, JSONEncodable, Hashable {

    public var keyHashType: PublicKeyHashType

    public init(keyHashType: PublicKeyHashType) {
        self.keyHashType = keyHashType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keyHashType = "key_hash_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keyHashType, forKey: .keyHashType)
    }
}

