//
// PublicKeyHashEcdsaSecp256k1AllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicKeyHashEcdsaSecp256k1AllOf: Codable, JSONEncodable, Hashable {

    /** Hex-encoded SHA-256 hash. */
    public var hashHex: String

    public init(hashHex: String) {
        self.hashHex = hashHex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hashHex = "hash_hex"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hashHex, forKey: .hashHex)
    }
}

