//
// ResourceAggregationLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ResourceAggregationLevel: String, Codable, CaseIterable {
    case global = "Global"
    case vault = "Vault"
}
