//
// RoleAssignmentResolution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RoleAssignmentResolution: String, Codable, CaseIterable {
    case explicit = "Explicit"
    case owner = "Owner"
}
