//
// RoyaltyAmount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoyaltyAmount: Codable, JSONEncodable, Hashable {

    public enum Unit: String, Codable, CaseIterable {
        case xrd = "XRD"
        case usd = "USD"
    }
    /** String-encoded decimal representing the amount of a related fungible resource. */
    public var amount: String
    public var unit: Unit

    public init(amount: String, unit: Unit) {
        self.amount = amount
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(unit, forKey: .unit)
    }
}

