//
// ScryptoSborValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScryptoSborValue: Codable, JSONEncodable, Hashable {

    /** Hex-encoded binary blob. */
    public var rawHex: String
    public var programmaticJson: ProgrammaticScryptoSborValue

    public init(rawHex: String, programmaticJson: ProgrammaticScryptoSborValue) {
        self.rawHex = rawHex
        self.programmaticJson = programmaticJson
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rawHex = "raw_hex"
        case programmaticJson = "programmatic_json"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rawHex, forKey: .rawHex)
        try container.encode(programmaticJson, forKey: .programmaticJson)
    }
}

