//
// StateKeyValueStoreDataRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateKeyValueStoreDataRequest: Codable, JSONEncodable, Hashable {

    public var atLedgerState: LedgerStateSelector?
    /** Bech32m-encoded human readable version of the address. */
    public var keyValueStoreAddress: String
    /** limited to max 100 items. */
    public var keys: [StateKeyValueStoreDataRequestKeyItem]

    public init(atLedgerState: LedgerStateSelector? = nil, keyValueStoreAddress: String, keys: [StateKeyValueStoreDataRequestKeyItem]) {
        self.atLedgerState = atLedgerState
        self.keyValueStoreAddress = keyValueStoreAddress
        self.keys = keys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case atLedgerState = "at_ledger_state"
        case keyValueStoreAddress = "key_value_store_address"
        case keys
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(atLedgerState, forKey: .atLedgerState)
        try container.encode(keyValueStoreAddress, forKey: .keyValueStoreAddress)
        try container.encode(keys, forKey: .keys)
    }
}

