//
// StateNonFungibleIdsResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateNonFungibleIdsResponseAllOf: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded human readable version of the address. */
    public var resourceAddress: String
    public var nonFungibleIds: NonFungibleIdsCollection

    public init(resourceAddress: String, nonFungibleIds: NonFungibleIdsCollection) {
        self.resourceAddress = resourceAddress
        self.nonFungibleIds = nonFungibleIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceAddress = "resource_address"
        case nonFungibleIds = "non_fungible_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resourceAddress, forKey: .resourceAddress)
        try container.encode(nonFungibleIds, forKey: .nonFungibleIds)
    }
}

