//
// StateEntityDetailsResponseItemDetailsType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum StateEntityDetailsResponseItemDetailsType: String, Codable, CaseIterable {
    case fungibleResource = "FungibleResource"
    case nonFungibleResource = "NonFungibleResource"
    case fungibleVault = "FungibleVault"
    case nonFungibleVault = "NonFungibleVault"
    case package = "Package"
    case component = "Component"
}
