//
// StateEntityFungiblesPageRequestAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateEntityFungiblesPageRequestAllOf: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded human readable version of the address. */
    public var address: String
    public var aggregationLevel: ResourceAggregationLevel?
    public var optIns: StateEntityFungiblesPageRequestOptIns?

    public init(address: String, aggregationLevel: ResourceAggregationLevel? = nil, optIns: StateEntityFungiblesPageRequestOptIns? = nil) {
        self.address = address
        self.aggregationLevel = aggregationLevel
        self.optIns = optIns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case aggregationLevel = "aggregation_level"
        case optIns = "opt_ins"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(aggregationLevel, forKey: .aggregationLevel)
        try container.encodeIfPresent(optIns, forKey: .optIns)
    }
}

