//
// StateEntityDetailsOptIns.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Check detailed [OptIns](#section/Using-endpoints-with-opt-in-features) documentation for more details */
public struct StateEntityDetailsOptIns: Codable, JSONEncodable, Hashable {

    /** if set to `true`, ancestor addresses - `parent_address`, `owner_address` and `global_address` for entities are returned. */
    public var ancestorIdentities: Bool? = false
    /** if set to `true`, `royalty_config` for component entities is returned. */
    public var componentRoyaltyConfig: Bool? = false
    /** if set to `true`, `royalty_vault_balance` for component entities is returned. */
    public var componentRoyaltyVaultBalance: Bool? = false
    /** if set to `true`, `royalty_vault_balance` for package entities is returned. */
    public var packageRoyaltyVaultBalance: Bool? = false
    /** if set to `true`, first page of non fungible ids are returned for each non fungible resource, with `next_cursor` which can be later used at `/state/entity/page/non-fungible-vault/ids` endpoint. */
    public var nonFungibleIncludeNfids: Bool? = false
    /** allows specifying explicitly metadata properties which should be returned in response. */
    public var explicitMetadata: [String]?

    public init(ancestorIdentities: Bool? = false, componentRoyaltyConfig: Bool? = false, componentRoyaltyVaultBalance: Bool? = false, packageRoyaltyVaultBalance: Bool? = false, nonFungibleIncludeNfids: Bool? = false, explicitMetadata: [String]? = nil) {
        self.ancestorIdentities = ancestorIdentities
        self.componentRoyaltyConfig = componentRoyaltyConfig
        self.componentRoyaltyVaultBalance = componentRoyaltyVaultBalance
        self.packageRoyaltyVaultBalance = packageRoyaltyVaultBalance
        self.nonFungibleIncludeNfids = nonFungibleIncludeNfids
        self.explicitMetadata = explicitMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ancestorIdentities = "ancestor_identities"
        case componentRoyaltyConfig = "component_royalty_config"
        case componentRoyaltyVaultBalance = "component_royalty_vault_balance"
        case packageRoyaltyVaultBalance = "package_royalty_vault_balance"
        case nonFungibleIncludeNfids = "non_fungible_include_nfids"
        case explicitMetadata = "explicit_metadata"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ancestorIdentities, forKey: .ancestorIdentities)
        try container.encodeIfPresent(componentRoyaltyConfig, forKey: .componentRoyaltyConfig)
        try container.encodeIfPresent(componentRoyaltyVaultBalance, forKey: .componentRoyaltyVaultBalance)
        try container.encodeIfPresent(packageRoyaltyVaultBalance, forKey: .packageRoyaltyVaultBalance)
        try container.encodeIfPresent(nonFungibleIncludeNfids, forKey: .nonFungibleIncludeNfids)
        try container.encodeIfPresent(explicitMetadata, forKey: .explicitMetadata)
    }
}

