//
// StateEntityDetailsResponseComponentDetailsAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateEntityDetailsResponseComponentDetailsAllOf: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded human readable version of the address. */
    public var packageAddress: String?
    public var blueprintName: String
    public var blueprintVersion: String
    /** A representation of a component's inner state. If this entity is a `GenericComponent`, this field will be in a programmatic JSON structure (you can deserialize it as a `ProgrammaticScryptoSborValue`). Otherwise, for \"native\" components such as `Account`, `Validator`, `AccessController`, `OneResourcePool`, `TwoResourcePool`, and `MultiResourcePool`, this field will be a custom JSON model defined in the Core API schema.  */
    public var state: AnyCodable?
    public var roleAssignments: ComponentEntityRoleAssignments?
    /** String-encoded decimal representing the amount of a related fungible resource. */
    public var royaltyVaultBalance: String?
    public var royaltyConfig: ComponentRoyaltyConfig?

    public init(packageAddress: String? = nil, blueprintName: String, blueprintVersion: String, state: AnyCodable? = nil, roleAssignments: ComponentEntityRoleAssignments? = nil, royaltyVaultBalance: String? = nil, royaltyConfig: ComponentRoyaltyConfig? = nil) {
        self.packageAddress = packageAddress
        self.blueprintName = blueprintName
        self.blueprintVersion = blueprintVersion
        self.state = state
        self.roleAssignments = roleAssignments
        self.royaltyVaultBalance = royaltyVaultBalance
        self.royaltyConfig = royaltyConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case packageAddress = "package_address"
        case blueprintName = "blueprint_name"
        case blueprintVersion = "blueprint_version"
        case state
        case roleAssignments = "role_assignments"
        case royaltyVaultBalance = "royalty_vault_balance"
        case royaltyConfig = "royalty_config"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(packageAddress, forKey: .packageAddress)
        try container.encode(blueprintName, forKey: .blueprintName)
        try container.encode(blueprintVersion, forKey: .blueprintVersion)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(roleAssignments, forKey: .roleAssignments)
        try container.encodeIfPresent(royaltyVaultBalance, forKey: .royaltyVaultBalance)
        try container.encodeIfPresent(royaltyConfig, forKey: .royaltyConfig)
    }
}

