//
// StateEntityDetailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateEntityDetailsResponse: Codable, JSONEncodable, Hashable {

    public var ledgerState: LedgerState
    public var items: [StateEntityDetailsResponseItem]

    public init(ledgerState: LedgerState, items: [StateEntityDetailsResponseItem]) {
        self.ledgerState = ledgerState
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ledgerState = "ledger_state"
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ledgerState, forKey: .ledgerState)
        try container.encode(items, forKey: .items)
    }
}

