//
// StateEntityDetailsRequestAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateEntityDetailsRequestAllOf: Codable, JSONEncodable, Hashable {

    public var optIns: StateEntityDetailsOptIns?
    /** limited to max 100 items. */
    public var addresses: [String]
    public var aggregationLevel: ResourceAggregationLevel?

    public init(optIns: StateEntityDetailsOptIns? = nil, addresses: [String], aggregationLevel: ResourceAggregationLevel? = nil) {
        self.optIns = optIns
        self.addresses = addresses
        self.aggregationLevel = aggregationLevel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case optIns = "opt_ins"
        case addresses
        case aggregationLevel = "aggregation_level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(optIns, forKey: .optIns)
        try container.encode(addresses, forKey: .addresses)
        try container.encodeIfPresent(aggregationLevel, forKey: .aggregationLevel)
    }
}

