//
// StateAccountResourcePreferencesPageRequestAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateAccountResourcePreferencesPageRequestAllOf: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded human readable version of the address. */
    public var accountAddress: String

    public init(accountAddress: String) {
        self.accountAddress = accountAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountAddress = "account_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountAddress, forKey: .accountAddress)
    }
}

