//
// StateKeyValueStoreKeysRequestAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateKeyValueStoreKeysRequestAllOf: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded human readable version of the address. */
    public var keyValueStoreAddress: String

    public init(keyValueStoreAddress: String) {
        self.keyValueStoreAddress = keyValueStoreAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keyValueStoreAddress = "key_value_store_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keyValueStoreAddress, forKey: .keyValueStoreAddress)
    }
}

