//
// StateEntityFungiblesPageRequestOptIns.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Check detailed [OptIns](#section/Using-endpoints-with-opt-in-features) documentation for more details */
public struct StateEntityFungiblesPageRequestOptIns: Codable, JSONEncodable, Hashable {

    /** allows specifying explicitly metadata properties which should be returned in response, limited to max 20 items. */
    public var explicitMetadata: [String]?

    public init(explicitMetadata: [String]? = nil) {
        self.explicitMetadata = explicitMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case explicitMetadata = "explicit_metadata"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(explicitMetadata, forKey: .explicitMetadata)
    }
}

