//
// StateEntityDetailsResponseNonFungibleResourceDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateEntityDetailsResponseNonFungibleResourceDetails: Codable, JSONEncodable, Hashable {

    public var type: StateEntityDetailsResponseItemDetailsType
    public var roleAssignments: ComponentEntityRoleAssignments
    public var nonFungibleIdType: NonFungibleIdType
    /** String-encoded decimal representing the amount of a related fungible resource. */
    public var totalSupply: String
    /** String-encoded decimal representing the amount of a related fungible resource. */
    public var totalMinted: String
    /** String-encoded decimal representing the amount of a related fungible resource. */
    public var totalBurned: String

    public init(type: StateEntityDetailsResponseItemDetailsType, roleAssignments: ComponentEntityRoleAssignments, nonFungibleIdType: NonFungibleIdType, totalSupply: String, totalMinted: String, totalBurned: String) {
        self.type = type
        self.roleAssignments = roleAssignments
        self.nonFungibleIdType = nonFungibleIdType
        self.totalSupply = totalSupply
        self.totalMinted = totalMinted
        self.totalBurned = totalBurned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case roleAssignments = "role_assignments"
        case nonFungibleIdType = "non_fungible_id_type"
        case totalSupply = "total_supply"
        case totalMinted = "total_minted"
        case totalBurned = "total_burned"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(roleAssignments, forKey: .roleAssignments)
        try container.encode(nonFungibleIdType, forKey: .nonFungibleIdType)
        try container.encode(totalSupply, forKey: .totalSupply)
        try container.encode(totalMinted, forKey: .totalMinted)
        try container.encode(totalBurned, forKey: .totalBurned)
    }
}

