//
// StreamTransactionsRequestEventFilterItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StreamTransactionsRequestEventFilterItem: Codable, JSONEncodable, Hashable {

    public enum Event: String, Codable, CaseIterable {
        case deposit = "Deposit"
        case withdrawal = "Withdrawal"
    }
    public var event: Event
    /** Bech32m-encoded human readable version of the address. */
    public var emitterAddress: String?
    /** Bech32m-encoded human readable version of the address. */
    public var resourceAddress: String?

    public init(event: Event, emitterAddress: String? = nil, resourceAddress: String? = nil) {
        self.event = event
        self.emitterAddress = emitterAddress
        self.resourceAddress = resourceAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
        case emitterAddress = "emitter_address"
        case resourceAddress = "resource_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(event, forKey: .event)
        try container.encodeIfPresent(emitterAddress, forKey: .emitterAddress)
        try container.encodeIfPresent(resourceAddress, forKey: .resourceAddress)
    }
}

