//
// StreamTransactionsRequestAllOfManifestClassFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StreamTransactionsRequestAllOfManifestClassFilter: Codable, JSONEncodable, Hashable {

    public var _class: ManifestClass
    public var matchOnlyMostSpecific: Bool? = false

    public init(_class: ManifestClass, matchOnlyMostSpecific: Bool? = false) {
        self._class = _class
        self.matchOnlyMostSpecific = matchOnlyMostSpecific
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _class = "class"
        case matchOnlyMostSpecific = "match_only_most_specific"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_class, forKey: ._class)
        try container.encodeIfPresent(matchOnlyMostSpecific, forKey: .matchOnlyMostSpecific)
    }
}

