//
// TransactionPreviewRequestFlags.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionPreviewRequestFlags: Codable, JSONEncodable, Hashable {

    public var useFreeCredit: Bool
    public var assumeAllSignatureProofs: Bool
    public var skipEpochCheck: Bool

    public init(useFreeCredit: Bool, assumeAllSignatureProofs: Bool, skipEpochCheck: Bool) {
        self.useFreeCredit = useFreeCredit
        self.assumeAllSignatureProofs = assumeAllSignatureProofs
        self.skipEpochCheck = skipEpochCheck
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case useFreeCredit = "use_free_credit"
        case assumeAllSignatureProofs = "assume_all_signature_proofs"
        case skipEpochCheck = "skip_epoch_check"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(useFreeCredit, forKey: .useFreeCredit)
        try container.encode(assumeAllSignatureProofs, forKey: .assumeAllSignatureProofs)
        try container.encode(skipEpochCheck, forKey: .skipEpochCheck)
    }
}

