//
// TransactionNonFungibleBalanceChanges.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionNonFungibleBalanceChanges: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded human readable version of the address. */
    public var entityAddress: String
    /** Bech32m-encoded human readable version of the address. */
    public var resourceAddress: String
    public var added: [String]
    public var removed: [String]

    public init(entityAddress: String, resourceAddress: String, added: [String], removed: [String]) {
        self.entityAddress = entityAddress
        self.resourceAddress = resourceAddress
        self.added = added
        self.removed = removed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entityAddress = "entity_address"
        case resourceAddress = "resource_address"
        case added
        case removed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entityAddress, forKey: .entityAddress)
        try container.encode(resourceAddress, forKey: .resourceAddress)
        try container.encode(added, forKey: .added)
        try container.encode(removed, forKey: .removed)
    }
}

