//
// TransactionStatusRequestAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionStatusRequestAllOf: Codable, JSONEncodable, Hashable {

    /** Bech32m-encoded hash. */
    public var intentHash: String

    public init(intentHash: String) {
        self.intentHash = intentHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case intentHash = "intent_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(intentHash, forKey: .intentHash)
    }
}

