//
// TransactionPreviewResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionPreviewResponse: Codable, JSONEncodable, Hashable {

    /** Hex-encoded binary blob. */
    public var encodedReceipt: String
    /** This type is defined in the Core API as `TransactionReceipt`. See the Core API documentation for more details.  */
    public var receipt: AnyCodable
    public var resourceChanges: [AnyCodable]
    public var logs: [TransactionPreviewResponseLogsInner]

    public init(encodedReceipt: String, receipt: AnyCodable, resourceChanges: [AnyCodable], logs: [TransactionPreviewResponseLogsInner]) {
        self.encodedReceipt = encodedReceipt
        self.receipt = receipt
        self.resourceChanges = resourceChanges
        self.logs = logs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case encodedReceipt = "encoded_receipt"
        case receipt
        case resourceChanges = "resource_changes"
        case logs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(encodedReceipt, forKey: .encodedReceipt)
        try container.encode(receipt, forKey: .receipt)
        try container.encode(resourceChanges, forKey: .resourceChanges)
        try container.encode(logs, forKey: .logs)
    }
}

