//
// ValidatorsUptimeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidatorsUptimeResponse: Codable, JSONEncodable, Hashable {

    public var ledgerState: LedgerState
    public var validators: ValidatorUptimeCollection

    public init(ledgerState: LedgerState, validators: ValidatorUptimeCollection) {
        self.ledgerState = ledgerState
        self.validators = validators
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ledgerState = "ledger_state"
        case validators
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ledgerState, forKey: .ledgerState)
        try container.encode(validators, forKey: .validators)
    }
}

