//
// ValidatorCollectionItemEffectiveFeeFactor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidatorCollectionItemEffectiveFeeFactor: Codable, JSONEncodable, Hashable {

    public var current: ValidatorCollectionItemEffectiveFeeFactorCurrent
    public var pending: ValidatorCollectionItemEffectiveFeeFactorPending?

    public init(current: ValidatorCollectionItemEffectiveFeeFactorCurrent, pending: ValidatorCollectionItemEffectiveFeeFactorPending? = nil) {
        self.current = current
        self.pending = pending
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case pending
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(current, forKey: .current)
        try container.encodeIfPresent(pending, forKey: .pending)
    }
}

