//
// ValidatorsUptimeResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidatorsUptimeResponseAllOf: Codable, JSONEncodable, Hashable {

    public var validators: ValidatorUptimeCollection

    public init(validators: ValidatorUptimeCollection) {
        self.validators = validators
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case validators
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(validators, forKey: .validators)
    }
}

