//
// ValidatorCollectionItemEffectiveFeeFactorCurrent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidatorCollectionItemEffectiveFeeFactorCurrent: Codable, JSONEncodable, Hashable {

    /** String-encoded decimal representing the amount of a related fungible resource. */
    public var feeFactor: String

    public init(feeFactor: String) {
        self.feeFactor = feeFactor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feeFactor = "fee_factor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feeFactor, forKey: .feeFactor)
    }
}

