//
// ValidatorCollectionItemEffectiveFeeFactorPending.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidatorCollectionItemEffectiveFeeFactorPending: Codable, JSONEncodable, Hashable {

    static let effectiveAtEpochRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: 10000000000, exclusiveMaximum: false, multipleOf: nil)
    /** String-encoded decimal representing the amount of a related fungible resource. */
    public var feeFactor: String
    public var effectiveAtEpoch: Int64

    public init(feeFactor: String, effectiveAtEpoch: Int64) {
        self.feeFactor = feeFactor
        self.effectiveAtEpoch = effectiveAtEpoch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feeFactor = "fee_factor"
        case effectiveAtEpoch = "effective_at_epoch"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feeFactor, forKey: .feeFactor)
        try container.encode(effectiveAtEpoch, forKey: .effectiveAtEpoch)
    }
}

