//
// StatisticsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class StatisticsAPI {

    /**
     Get Validators Uptime
     
     - parameter validatorsUptimeRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func validatorsUptime(validatorsUptimeRequest: ValidatorsUptimeRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ValidatorsUptimeResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return validatorsUptimeWithRequestBuilder(validatorsUptimeRequest: validatorsUptimeRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Validators Uptime
     - POST /statistics/validators/uptime
     - Returns validators uptime data for time range limited by `from_state_version` and `at_state_version`. 
     - parameter validatorsUptimeRequest: (body)  
     - returns: RequestBuilder<ValidatorsUptimeResponse> 
     */
    open class func validatorsUptimeWithRequestBuilder(validatorsUptimeRequest: ValidatorsUptimeRequest) -> RequestBuilder<ValidatorsUptimeResponse> {
        let localVariablePath = "/statistics/validators/uptime"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: validatorsUptimeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ValidatorsUptimeResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
